removed the top margin that caused a shift in the vertical centering,
Hack4Impact-UMD/umd-website-redesign pull request #74
Opened 2022-08-16 19:28 UTC by surabi0516

now the navbar items should be vertically centerd

2022-08-20 18:07 UTC, heylookitsme requested changes
likely this is not the top margin

2022-08-20 18:07 UTC, heylookitsme commented on frontend/src/styles/navbar/Navbar.module.css
> -  margin-top: 23px;
uh 

![image](https://user-images.githubusercontent.com/45301066/185760581-6702eed9-3d34-47be-8ba6-20f877e7e66f.png)

2022-08-20 18:07 UTC, heylookitsme commented on frontend/src/styles/navbar/Navbar.module.css
> -  margin-top: 23px;
+ chrome 

![image](https://user-images.githubusercontent.com/45301066/185760605-511eea09-1166-4af1-8651-6f87f241f378.png)

2022-09-27 04:23 UTC, Stephboss9 reviewed
Top margin is not reason for shift in vertical centering. Closing this PR request.

2022-09-27 04:23 UTC, closed without merging